scrape_configs:
  - job_name: 'spring-playground'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ['learning-core:8080']